blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Authentication Routes...
Route::get('Admin/auth/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('Admin/auth/login', 'Auth\LoginController@login');
Route::post('Admin/auth/logout', 'Auth\LoginController@logout')->name('logout');

//RUTAS DEL MODULO DE ADMINISTRACION
Route::group(['prefix' => 'Admin' , 'middleware' => ['auth']], function()
{
    //Usuarios
    Route::resource('Users' , 'UsersController');
    Route::get('User/{id}/destroy' , [
    	'uses' => 'UsersController@destroy',
    	'as'  => 'Users.destroy'

    ]);
    //Categorias
    Route::resource('Categories' , 'CategoriesController');
    Route::get('Category/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'Categories.destroy'
    ]);
    //Tags
    Route::resource('Tags' , 'TagsController');
    Route::get('Tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'Tags.destroy'
    ]);
    //Articulos
    Route::resource('articles' , 'ArticlesController');
    Route::get('article/{id}/destroy', [
        'uses' => 'ArticlesController@destroy',
        'as' => 'articles.destroy'
    ]);


});



//RUTAS DEL MODULO DE USUARIOS
   Route::get('/', 'HomeController@index')->name('home');

   Route::get('homepage', function() {
       return view('welcome');
   })->name('homepage');


   //busqueda de categorias
   Route::get('categories/{name}' , [
     'uses' => 'HomeController@seachCategory',
     'as' => 'seach.category'
   ]);

   //busqueda de tags
   Route::get('tags/{name}' , [
     'uses' => 'HomeController@seachTag',
     'as' => 'seach.tag'
   ]);

    //listado de articulos
    Route::get('articles/index1', [
        'uses' => 'ArticlesController@showArticles',
        'as' => 'Articles.index1'
   ]);

    //Imagenes
    Route::get('images.index', [
        'uses'  => 'ImagesController@show',
        'as'    => 'images.index'

    ]);

blog/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";

    protected $fillable = ['name'];

    public function articles()
    {
    	return $this->hasMany('App\Article');
    }

    public function scopeSearchCategory($query, $name)
    {
      return $query->where('name' , '=' , $name );
    }
}

blog/app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Category;
use Laracasts\Flash\Flash;

class CategoriesController extends Controller
{
	public function index()
    {
    	$categories = Category::orderby('id' , 'ASC')->paginate(5);
    	return view('Admin.categories.index')->with('categories' , $categories);
    }

    public function store(CategoryRequest $request)
    {
    	$category = new Category($request->all());
    	$category->save();

    	Flash::success('La categoria ' . $category->name . ' ha sido guardada con exito');
    	return redirect()->route('Categories.index');
    	
    }


    public function create()
    {
    	return view('Admin.categories.create');
    }

     public function edit($id)
    {
        $category = Category::Find($id);
        return view('Admin.categories.edit')->with('category' , $category);
    }

     public function destroy($id)
    { 
        $category = Category::Find($id);      
        Flash::error('Se ha elimino la categoria ' . $category->name . ' de forma exitosa');
        $category->delete(); 
        return redirect()->route('Categories.index');
    }
      public function update(request $request , $id)
    {
        $category = Category::Find($id);
        $category->fill($request->all());
        $category->save();

        Flash::warning('La categoria ' . $category->name . ' ha sido editada con exito');
        return redirect()->route('Categories.index'); 
    }
}

blog/resources/views/Admin/categories/create.blade.php
@extends('Admin.template.main')

@section('title' , 'Categorias')
@section('subtitle' , '\ Agregar categoria')


@section('inner')

{!! Form::open(['route' => 'Categories.store' , 'method' => 'POST']) !!} 
<br>
<div class="form-group">
	{!!	Form::label('name' , 'Nombre')!!}
	{!! Form::text('name' , null, ['class' => 'form-control', 'placeholder' => 'Nombre de la categoria' , 'required']) !!}
	
</div>
<br>
<div class="form-group">
	{!!	Form::submit('Registar' , ['class' => 'btn btn-primary'])!!}
	
</div>

{!! Form::close() !!}
@endsection

blog/resources/views/Admin/categories/edit.blade.php
@extends('Admin.template.main')

@section('subtitle', '\  Editar categoria ' . $category->name)

@section('inner')

{!! Form::open(['route' => ['Categories.update', $category], 'method' => 'PUT']) !!}

<div class="form-group">
	<br>
	{!!	Form::label ('name' , 'Nombre' )!!}
	{!!	Form::text ('name' , $category->name , ['class' => 'form-control' , 'placeholder' => 'Nombre Completo' , 'required'] )!!}
	
</div>

<div class="form-group">
	<br>
	{!!	Form::submit ('Guardar' , ['class' => 'btn btn-primary'])!!}
	
</div>

{!! Form::close() !!} 

@endsection

blog/resources/views/Admin/categories/index.blade.php
@extends('Admin.template.main')

@section('title' , 'Categorias')
@section('subtitle' , '\ Listado de categorias')


@section('inner')
<br>
<a href="{{ route('Categories.create') }}" class="button primary">
	<i  href="" class="fa fa-newspaper-o " > Agregar categoria</i>
</a>
<hr>
<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Nombre</th>
			<th>Accion</th>

		</tr>
	</thead>
	<tbody>
	    @foreach($categories as $category)
			<tr>
			 <td>{{ $category->id }}</td>
			 <td>{{ $category->name }}</td>
			 <td>

			 	<a href="{{ route('Categories.edit', $category->id) }}" class="button">
							<i  href="" class="fa fa-pencil-square-o" aria-hidden="true"> Editar</i>
				</a>

				<a href="{{ route('Categories.destroy' , $category->id) }}" onclick="return confirm('¿seguro que deseas eliminar este usuario?')" class="button primary">
				             <i  href="" class="fa fa-trash" aria-hidden="true"> Borrar</i>
			    </a>
			 </td>
		    </tr>
		@endforeach
	</tbody>
</table>
@endsection