blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Authentication Routes...
Route::get('Admin/auth/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('Admin/auth/login', 'Auth\LoginController@login');
Route::post('Admin/auth/logout', 'Auth\LoginController@logout')->name('logout');

//RUTAS DEL MODULO DE ADMINISTRACION
Route::group(['prefix' => 'Admin' , 'middleware' => ['auth']], function()
{
    //Usuarios
    Route::resource('Users' , 'UsersController');
    Route::get('User/{id}/destroy' , [
    	'uses' => 'UsersController@destroy',
    	'as'  => 'Users.destroy'

    ]);
    //Categorias
    Route::resource('Categories' , 'CategoriesController');
    Route::get('Category/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'Categories.destroy'
    ]);
    //Tags
    Route::resource('Tags' , 'TagsController');
    Route::get('Tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'Tags.destroy'
    ]);
    //Articulos
    Route::resource('articles' , 'ArticlesController');
    Route::get('article/{id}/destroy', [
        'uses' => 'ArticlesController@destroy',
        'as' => 'articles.destroy'
    ]);


});



//RUTAS DEL MODULO DE USUARIOS
   Route::get('/', 'HomeController@index')->name('home');

   Route::get('homepage', function() {
       return view('welcome');
   })->name('homepage');


   //busqueda de categorias
   Route::get('categories/{name}' , [
     'uses' => 'HomeController@seachCategory',
     'as' => 'seach.category'
   ]);

   //busqueda de tags
   Route::get('tags/{name}' , [
     'uses' => 'HomeController@seachTag',
     'as' => 'seach.tag'
   ]);

    //listado de articulos
    Route::get('articles/index1', [
        'uses' => 'ArticlesController@showArticles',
        'as' => 'Articles.index1'
   ]);

    //Imagenes
    Route::get('images.index', [
        'uses'  => 'ImagesController@show',
        'as'    => 'images.index'

    ]);

blog/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";

    protected $fillable = ['name'];

    public function articles()
    {
    	return $this->belongsToMany('App\Article')->withTimestamps();
    }

    public function scopeSearch($query, $name)
    {
    	return $query->where('name', 'LIKE', "%$name%");

    }

    public function scopeSearchTag($query, $name)
    {
      return $query->where('name' , '=' , $name );
    }
}

blog/app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;
use App\Tag;
use Laracasts\Flash\Flash;

class TagsController extends Controller
{
    public function index(request $request)
    {
        $tags = Tag::Search($request->name)->orderBy('id' , 'DESC')->paginate(5);
    	return view('Admin.tags.index')->with('tags', $tags);

    }

    public function create()
    {
    	return view('Admin.tags.create');

    }

    public function edit($id)
    {
        $tag = Tag::find($id);
    	return view('Admin.tags.edit')->with('tag' , $tag); 

    }

    public function store(TagRequest $request)
    {
        $tag = new Tag($request->all());
        $tag->save();

        Flash::success('El tag ' . $tag->name . ' ha sido creada con exito!');
        return redirect()->route('Tags.index');
    }

    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();

         Flash::success('El tag ' . $tag->name . ' ha sido eliminado con exito!');
        return redirect()->route('Tags.index');
    }

    public function update(request $request , $id)
    {
        $tag = Tag::Find($id);
        $tag->fill($request->all());
        $tag->save();

        Flash::warning('El Tag ' . $tag->name . ' ha sido editado con exito');
        return redirect()->route('Tags.index'); 
    }
}

blog/resources/views/Admin/tags/create.blade.php
@extends('Admin.template.main')

@section('title' , 'Agregar Tags')
@section('subtitle' , '\ Agregar Tag')


@section('inner')

{!! Form::open(['route' => 'Tags.store' , 'method' => 'POST']) !!} 
<br>
<div class="form-group">
	{!!	Form::label('name' , 'Nombre')!!}
	{!! Form::text('name' , null, ['class' => 'form-control', 'placeholder' => 'Nombre del tag' , 'required']) !!}
	
</div>
<br>
<div class="form-group">
	{!!	Form::submit('Registar' , ['class' => 'btn btn-primary'])!!}
	
</div>

{!! Form::close() !!}
@endsection

blog/resources/views/Admin/tags/edit.blade.php
@extends('Admin.template.main')

@section('subtitle', '\  Editar tag ' . $tag->name)

@section('inner')

{!! Form::open(['route' => ['Tags.update', $tag], 'method' => 'PUT']) !!}

<div class="form-group">
	<br>
	{!!	Form::label ('name' , 'Nombre' )!!}
	{!!	Form::text ('name' , $tag->name , ['class' => 'form-control' , 'placeholder' => 'Nombre Completo' , 'required'] )!!}
	
</div>

<div class="form-group">
	<br>
	{!!	Form::submit ('Guardar' , ['class' => 'btn btn-primary'])!!}
	
</div>

{!! Form::close() !!} 

@endsection

blog/resources/views/Admin/tags/index.blade.php
@extends('Admin.template.main')

@section('title' , 'Tags')
@section('subtitle' , '\ Listado de Tags')


@section('inner')
<!-- Boton para agregar un tag -->
<br>
<a href="{{ route('Tags.create') }}" class="button primary">
	<i  href="" class="fa fa-hashtag " > Agregar Tag</i>
</a>
<!-- buscador de tagas-->
{!! Form::open(['route' => 'Tags.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
	<div class="form-group">
		{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Buscar Tag...', 'aria-describedby' => 'search']) !!}
		<!--<span class="input-group-addon" id="search"><span class="fa fa-search"></span></span>-->
	</div>
{!! Form::close() !!}
<!--Tabla de los tags existentes -->
<hr>
<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Nombre</th>
			<th>Accion</th>

		</tr>
	</thead>
	<tbody>
		 @foreach($tags as $tag)
			<tr>
			 <td>{{ $tag->id }}</td>
			 <td>{{ $tag->name }}</td>
			 <td>

			 	<a href="{{ route('Tags.edit', $tag->id) }}" class="button">
							<i  href="" class="fa fa-pencil-square-o" aria-hidden="true"> Editar</i>
				</a>

				<a href="{{ route('Tags.destroy' , $tag->id) }}" onclick="return confirm('¿seguro que deseas eliminar este usuario?')" class="button primary">
				             <i  href="" class="fa fa-trash" aria-hidden="true"> Borrar</i>
			    </a>
			 </td>
		    </tr>
		@endforeach
	</tbody>
</table>
<div class="text-center">
	{!! $tags->render() !!}
</div>
@endsection