blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Authentication Routes...
Route::get('Admin/auth/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('Admin/auth/login', 'Auth\LoginController@login');
Route::post('Admin/auth/logout', 'Auth\LoginController@logout')->name('logout');

//RUTAS DEL MODULO DE ADMINISTRACION
Route::group(['prefix' => 'Admin' , 'middleware' => ['auth']], function()
{
    //Usuarios
    Route::resource('Users' , 'UsersController');
    Route::get('User/{id}/destroy' , [
    	'uses' => 'UsersController@destroy',
    	'as'  => 'Users.destroy'

    ]);
    //Categorias
    Route::resource('Categories' , 'CategoriesController');
    Route::get('Category/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'Categories.destroy'
    ]);
    //Tags
    Route::resource('Tags' , 'TagsController');
    Route::get('Tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'Tags.destroy'
    ]);
    //Articulos
    Route::resource('articles' , 'ArticlesController');
    Route::get('article/{id}/destroy', [
        'uses' => 'ArticlesController@destroy',
        'as' => 'articles.destroy'
    ]);


});



//RUTAS DEL MODULO DE USUARIOS
   Route::get('/', 'HomeController@index')->name('home');

   Route::get('homepage', function() {
       return view('welcome');
   })->name('homepage');


   //busqueda de categorias
   Route::get('categories/{name}' , [
     'uses' => 'HomeController@seachCategory',
     'as' => 'seach.category'
   ]);

   //busqueda de tags
   Route::get('tags/{name}' , [
     'uses' => 'HomeController@seachTag',
     'as' => 'seach.tag'
   ]);

    //listado de articulos
    Route::get('articles/index1', [
        'uses' => 'ArticlesController@showArticles',
        'as' => 'Articles.index1'
   ]);

    //Imagenes
    Route::get('images.index', [
        'uses'  => 'ImagesController@show',
        'as'    => 'images.index'

    ]);

blog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function articles()
    {
        return $this->hasMany('App\Article'); 
    }
}

blog/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Laracasts\Flash\Flash;
use App\Http\Requests\UserRequest;

class UsersController extends Controller
{
   

    //index
    public function index()
    {
    	$users = User::orderby('id' , 'ASC')->paginate(5);
    	return view('Admin.users.index')->with('users', $users);
    }

    //create
    public function create()
    {
    	return view('Admin.users.create');
    }

    //store
    public function store(UserRequest $request)
    {
    	$user = new User($request->all());
    	$user->password = bcrypt($request->password);
    	$user->save();
        Flash::success("Se ha registrado " . $user->name . " de forma exitosa");
    	return redirect()->route('Users.index');
    }

    public function destroy($id)
    { 
        $user = User::Find($id);      
        Flash::error('Se ha elimino el usuario de forma exitosa, adios  '  . $user->name);
        $user->delete(); 
        return redirect()->route('Users.index');

    }

    public function edit($id)
    {
        $user = User::Find($id);
        return view('Admin.users.edit')->with('user' , $user);
    }

    public function update(request $request , $id)
    {
        $user = User::Find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->type = $request->type;
        $user->save();

        Flash::warning('El usuario ' . $user->name . ' ha sido editado con exito');
        return redirect()->route('Users.index'); 
    }

}

blog/resources/views/Admin/users/create.blade.php
@extends('Admin.template.main')

@section('subtitle',' / Crear usario')

@section('inner')
   

   
	{!! Form::open(['route' => 'Users.store', 'method' => 'POST']) !!}

	<div class="form-group">
		<br>
		{!!	Form::label ('name' , 'Nombre' )!!}
		{!!	Form::text ('name' , null , ['class' => 'form-control' , 'placeholder' => 'Nombre Completo' , 'required'] )!!}
		
	</div>

	<div class="form-group">
		<br>
		{!!	Form::label ('email' , 'Correo Electronico' )!!}
		{!!	Form::email ('email' , null , ['class' => 'form-control' , 'placeholder' => 'example@gmail.com' , 'required'] )!!}
		
	</div>

	<div class="form-group">
		<br>
		{!!	Form::label ('password' , 'Contraseña' )!!}
		{!!	Form::password ('password' ,  ['class' => 'form-control' , 'placeholder' => '********' , 'required'] )!!}
		
	</div>

	<div class="form-group">
		<br>
		{!!	Form::label ('type' , 'Tipo' )!!}
		{!!	Form::select ('type' ,  ['member' => 'Miembro' , 'admin' => 'Administrador'], null , ['class' => 'form-control', 'placeholder' => 'Seleccione el tipo de usuario...', 'required']) !!}
		
	</div>

	<div class="form-group">
		<br>
		{!!	Form::submit ('Resgistar' , ['class' => 'btn btn-primary'])!!}
		
	</div>

	{!! Form::close() !!} 

@endsection

	

blog/resources/views/Admin/users/edit.blade.php
@extends('Admin.template.main')

@section('subtitle', '\  Editar usuario ' . $user->name)

@section('inner')

{!! Form::open(['route' => ['Users.update', $user], 'method' => 'PUT']) !!}

<div class="form-group">
	<br>
	{!!	Form::label ('name' , 'Nombre' )!!}
	{!!	Form::text ('name' , $user->name , ['class' => 'form-control' , 'placeholder' => 'Nombre Completo' , 'required'] )!!}
	
</div>

<div class="form-group">
	<br>
	{!!	Form::label ('email' , 'Correo Electronico' )!!}
	{!!	Form::email ('email' , $user->email , ['class' => 'form-control' , 'placeholder' => 'example@gmail.com' , 'required'] )!!}
	
</div>

<div class="form-group">
	<br>
	{!!	Form::label ('type' , 'Tipo' )!!}
	{!!	Form::select ('type' ,  [ 'member' => 'Miembro' , 'admin' => 'Administrador'], $user->type, ['class' => 'form-control'])!!}
	
</div>

<div class="form-group">
	<br>
	{!!	Form::submit ('Guardar' , ['class' => 'btn btn-primary'])!!}
	
</div>

{!! Form::close() !!} 

@endsection

blog/resources/views/Admin/users/index.blade.php
@extends('Admin.template.main')

@section('subtitle', '\  Lista Usuarios')

@section('inner')
<br>
<a href="{{ route('Users.create') }}" class="button primary">
	<i  href="" class="fa fa-user-plus " > Agregar</i>
</a>
<br>
<br>
 <table class="table-wrapper">
 	<thead >
 		<tr>
 			<th>ID</th>
 			<th>Nombre</th>
 			<th>Email</th>
 			<th>Tipo</th>
 			<th>Accion</th>
 		</tr>
 	</thead>
 	<tbody>
 		@foreach($users as $user)
	 		<tr>
	 			 <td>{{ $user->id  }}</td>
		         <td>{{ $user->name }}</td>
		         <td>{{ $user->email }}</td>
		         <td>
		         	@If( $user->type == "member")
                         <span class="alert alert-primary">{{ $user->type }}</span>
		         	@else
                          <span class="label label-success">{{ $user->type }}</span>
		         	@endif
		         	
		         </td>
		         <td> 
		            <a href="{{ route('Users.edit', $user->id) }}" class="button ">
							<i  href="" class="fa fa-pencil-square-o" aria-hidden="true"> Editar</i>
					</a>		
					<a href="{{ route('Users.destroy' , $user->id) }}" onclick="return confirm('¿seguro que deseas eliminar este usuario?')" class="button primary">
							<i  href="{{ route('Users.destroy' , $user->id) }}" class="fa fa-trash" aria-hidden="true"> Borrar</i>
					</a>					
		         </td>
	 		</tr>	         
 		@endforeach
 	</tbody>
 </table>
 <div class="" align="center">
 	 {!! $users->render() !!}
 </div>


@endsection