blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Authentication Routes...
Route::get('Admin/auth/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('Admin/auth/login', 'Auth\LoginController@login');
Route::post('Admin/auth/logout', 'Auth\LoginController@logout')->name('logout');

//RUTAS DEL MODULO DE ADMINISTRACION
Route::group(['prefix' => 'Admin' , 'middleware' => ['auth']], function()
{
    //Usuarios
    Route::resource('Users' , 'UsersController');
    Route::get('User/{id}/destroy' , [
    	'uses' => 'UsersController@destroy',
    	'as'  => 'Users.destroy'

    ]);
    //Categorias
    Route::resource('Categories' , 'CategoriesController');
    Route::get('Category/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'Categories.destroy'
    ]);
    //Tags
    Route::resource('Tags' , 'TagsController');
    Route::get('Tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'Tags.destroy'
    ]);
    //Articulos
    Route::resource('articles' , 'ArticlesController');
    Route::get('article/{id}/destroy', [
        'uses' => 'ArticlesController@destroy',
        'as' => 'articles.destroy'
    ]);


});



//RUTAS DEL MODULO DE USUARIOS
   Route::get('/', 'HomeController@index')->name('home');

   Route::get('homepage', function() {
       return view('welcome');
   })->name('homepage');


   //busqueda de categorias
   Route::get('categories/{name}' , [
     'uses' => 'HomeController@seachCategory',
     'as' => 'seach.category'
   ]);

   //busqueda de tags
   Route::get('tags/{name}' , [
     'uses' => 'HomeController@seachTag',
     'as' => 'seach.tag'
   ]);

    //listado de articulos
    Route::get('articles/index1', [
        'uses' => 'ArticlesController@showArticles',
        'as' => 'Articles.index1'
   ]);

    //Imagenes
    Route::get('images.index', [
        'uses'  => 'ImagesController@show',
        'as'    => 'images.index'

    ]);

blog/resources/views/Admin/template/partials/Banner.blade.php
<!-- Banner -->
<section id="banner">
	<div class="content">
		<header>
			<h1>PRODEPORTE<br />
			2000</h1>
			<p>CIRCUITO ESTATAL DE VOLEIBOL DE PLAYA II</p>
		</header>
		<p style="align-content: center; ">LA LIGA CEDVP, ES UNA ORGANIZACIÓN DEPORTIVA INTERESCOLAR QUE PRETENDE DESARROLLAR EN SUS PARTICIPANTES EL SENTIDO DE RESPONSABILIDAD, EL ESFUERZO Y DISCIPLINA A TRAVÉS DE LA COMPETENCIA ASÍ COMO EL APOYO Y EJEMPLO DE LOS ADULTOS EN SU COMPORTAMIENTO..</p>
		<ul class="actions">
			<li><a href="#" class="button big">Learn More</a></li>
		</ul>
	</div>
	<span class="image object">
		<img src="{{ asset('plugins/images/pic012.jpg') }}" alt="" />
	</span>
</section>

blog/resources/views/Admin/template/partials/errors.blade.php
	@if(count($errors) > 0)
		<div class="alert alert-danger" role = "alert">
			<ul>
				@foreach($errors->all() as $error)
					<li> {{ $error }}</li>
			    @endforeach			
			</ul>
		</div>
	@endif

blog/resources/views/Admin/template/partials/header.blade.php
<!-- Header -->
<header id="header">
	<a href="{{ route('home') }}" class="logo"><strong>Liga De Voleibol De Playa</strong>  @yield('subtitle')</a>

	<!-- icosnos de faceboook ..... -->
    <ul class="icons">			
		<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
		<li>
			<a href="{{ url('https://www.facebook.com/ProdeporteVoleibolPlaya/') }}" class="icon fa-facebook"><span class="label">Facebook</span></a>
		</li>
		<li><a href="#" class="icon fa-snapchat-ghost"><span class="label">Snapchat</span></a></li>
		<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>	
	@if(Auth::user())
		<li>
			<span class="opener">{{ Auth::user()->name }}</span>
		</li>
		<li>
			<form action="{{ route('logout') }}" method="POST" >
			     {{ csrf_field() }}	
			     <button class="button small" ><i class="fa fa-sign-in" > logout</i></button>
	        </form>
	    </li>
	@else
	 	 <li>
	 	 	<a href="{{ route('login') }}">
		 		<h4>
		 			<i  href="" class="fa fa-sign-in" > login</i>
		 		</h4>
			</a> 											
     	</li>
	@endif			
	</ul>
	
</header>

blog/resources/views/Admin/template/partials/navigation.blade.php
<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<!-- Search -->
							<!-- buscador de articulos-->
						        {!! Form::open(['route' => 'Articles.index1', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
						            <div class="form-group">
						                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Buscar Articulo...', 'aria-describedby' => 'search']) !!}
						            </div>
						        {!! Form::close() !!}
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
									@if(Auth::user())
										<li>
											<span class="opener">{{ Auth::user()->name }}</span>
											<ul>
												<li>
													<form action="{{ route('logout') }}" method="POST" >
													     {{ csrf_field() }}
													     <button class="btn btn-danger" ><i class="fa fa-sign-in" > logout</i></button>
											        </form>
											    </li>
											</ul>
										</li>
								    @endif
										<li><a href="{{ route('homepage') }}">Home</a></li>
									@if(Auth::user())
										<li><a href="{{ url('Admin/Users') }}">Usuarios</a></li>
										<li><a href="{{ url('Admin/Categories') }}">Categorias</a></li>
									@endif
										<li>
											<span class="opener">Articulos</span>
											<ul>
										@if(Auth::user())
										      <li><a href="{{ route('articles.create') }}">Crear articulo </a></li>
											  <li><a href="{{ route('articles.index') }}">Listado de articulos</a></li>
										@endif
												<!-- se debe quitar esta linea despues -->
												<li><a href="{{ route('Articles.index1') }}">Vista de los articulos </a></li>
											</ul>
										</li>
										<li><a href="{{ route('images.index') }}">Imagenes</a></li>
										@if(Auth::user())
										<li><a href="{{ url('Admin/Tags') }}">Tags</a></li>
										@endif
									</ul>
								</nav>
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Contactanos</h2>
									</header>
									<p>El Instituto del Deporte y la Recreación del Estado de Querétaro (INDEREQ) y PRODEPORTE, con el aval de la Asociación Estatal de Querétaro de Voleibol y de la Comisión Permanente de Voleibol de playa del Estado de Querétaro, invitan a los jugadores y jugadoras de voleibol de playa, y al público en general, a participar en Circuito Estatal de Voleibol de Playa PRODEPORTE-2000</p>
									<ul class="contact">
										<li class="fa-envelope-o"><a href="#">octaviomedinag@hotmail.com</a></li>
										<li class="fa-phone">(442) 128-0509</li>
										<li class="fa-map-marker"><h5><font style="vertical-align: inherit;"><font class="goog-text-highlight" style="vertical-align: inherit;">PARQUE QUERETARO 2000</font></font></h5>Blvd. Bernanrdo Quintana SN<br />
										   Col. Villas del Parque <br>
									       Querétaro, Qro.
									    </li>
									    <li class="fa-map-marker"><h5><font style="vertical-align: inherit;"><font class="goog-text-highlight" style="vertical-align: inherit;">AUDITORIO ARTEAGA</font></font></h5>Av. Universidad no. 13 Pte.<br />
									    	Centro Histórico <br />
									    	Queretaro, Qro.
									    </li>
									</ul>
								</section>
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Nuestros servicios</h2>
									</header>
									<div class="mini-posts">
										<article>
											<a href="#" class="image"><img src="{{ asset('plugins/images/pic04.jpg') }}" alt="" /></a>
											<h4><font style="vertical-align: inherit;"><font class="goog-text-highlight" style="vertical-align: inherit;">PREPARACIÓN FÍSICA</font></font></h4>
											<p>Desarrollamos tu máximo potencial deportivo a través de ejercicios específicos de tu deporte, complementándolo con un plan de alimentación adecuado y rutinas alternas que te harán llegar al siguiente nivel</p>
										</article>
										<article>
											<a href="#" class="image"><img src="{{ asset('plugins/images/pic02.jpg') }}" alt="" /></a>
											<h4><font style="vertical-align: inherit;"><font class="goog-text-highlight" style="vertical-align: inherit;">ANTROPOMETRIA DEPORTIVA</font></font></h4>
											<p>Vamos a conocer tu estructura y composición corporal para determinar y explotar al máximo tus mejores habilidades deportivas.</p>
										</article>
										<article>
											<a href="#" class="image"><img src="{{ asset('plugins/images/pic03.jpg') }}" alt="" /></a>
											<h4><font style="vertical-align: inherit;"><font class="goog-text-highlight" style="vertical-align: inherit;">NEUROENTRENAMIENTO DEPORTIVO</font></font></h4>
											<p>Tu mente puede llevar a tu cuerpo a niveles que jamas imaginarias que puedes llegar</p>
										</article>
									</div>
									<ul class="actions">
										<li><a href="{{ route('homepage') }}" class="button">Mas sobre nosotros</a></li>
									</ul>
								</section>
							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">&copy; PRODEPORTE-2000. All rights reserved. <a href="https://unsplash.com">Unsplash</a>. Design: <a href="">Julian Mondragon</a>.</p>
								</footer>

						</div>

blog/resources/views/Admin/template/partials/section1.blade.php
<!-- Section 1 -->
<section>
	<header class="major">
		<h2>Diciplinas</h2>
	</header>
	<div class="features">
		<article>
			<span class="icon fa-dribbble"></span>
			<div class="content">
				<h3>VOLEIBOL DE SALA</h3>
				<p>Entrena con nostros esta clásica disciplina de deporte en equipo y participa en torneos nacionales e internacionales.</p>
			</div>
		</article>
		<article>
			<span class=" icon fa-dribbble"></span>

			<div class="content">
				<h3>VOLEIBOL DE PLAYA</h3>
				<p>Ven a entrenar con nosotros en las mejores instalaciones de arena del estado,  en esta disciplina Olímpica que tanto gusta a los espectadores.</p>
			</div>
		</article>
		<article>
			<span class="icon fa-futbol-o"></span>
			<div class="content">
				<h3>FUTBOL DE PLAYA</h3>
				<p>Prueba esta variante del futbol donde desarrollarás tu agilidad, velocidad y precisión de tiro.</p>
			</div>
		</article>
		<article>
			<span class="icon fa-signal"></span>
			<div class="content">
				<h3>Sed magna finibus</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
			</div>
		</article>
	</div>
</section>

blog/resources/views/Admin/template/partials/section2.blade.php
<!-- Section -->
	<section>
		<header class="major">
			<h2>Ipsum sed dolor</h2>
		</header>
		<div class="posts">
			<article>
				<a href="#" class="image"><img src="images/pic01.jpg" alt="" /></a>
				<h3>Interdum aenean</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
			<article>
				<a href="#" class="image"><img src="images/pic02.jpg" alt="" /></a>
				<h3>Nulla amet dolore</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
			<article>
				<a href="#" class="image"><img src="images/pic03.jpg" alt="" /></a>
				<h3>Tempus ullamcorper</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
			<article>
				<a href="#" class="image"><img src="images/pic04.jpg" alt="" /></a>
				<h3>Sed etiam facilis</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
			<article>
				<a href="#" class="image"><img src="images/pic05.jpg" alt="" /></a>
				<h3>Feugiat lorem aenean</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
			<article>
				<a href="#" class="image"><img src="images/pic06.jpg" alt="" /></a>
				<h3>Amet varius aliquam</h3>
				<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
				<ul class="actions">
					<li><a href="#" class="button">More</a></li>
				</ul>
			</article>
		</div>
	</section>